[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.117.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  GO_VERSION = "1.21.0"
  NODE_VERSION = "18"

# Not using preview nor branch deployment yet
# See:
#  https://www.netlify.com/blog/2017/11/16/get-full-control-over-your-deployed-branches/
#  https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/
#  https://gohugo.io/hosting-and-deployment/hosting-on-netlify/

[context.branch-deploy.environment]
  HUGO_VERSION = "0.117.0"
  GO_VERSION = "1.21.0"
  NODE_VERSION = "18"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.117.0"
  GO_VERSION = "1.21.0"
  NODE_VERSION = "18"
